### ISSUE TITLE
Validate input for brush name

### ISSUE THREAD

**Issue by Ethspresso** [acamposuribe/p5.brush#10]
Using `brush.set()` to set the brush to an unknown string value like a brush name with a typo in it, raises ```TypeError: Cannot read properties of undefined (reading 'param')```

Expected result: An error message saying this is not a valid brush name.

![Screenshot from 2023-11-24 09-13-16](https://github.com/acamposuribe/p5.brush/assets/104690012/ced958c3-fd9f-4257-8494-0bcf46abe410)

Tested using the non-minified v1.0.3 in the p5js.org editor.

**Comment by acamposuribe** [comment]
Hi!
I've included error messages for several functions, but only for the full version
The minified version avoids these messages to compress the code as much as possible
