### ISSUE TITLE
Animations being very slow

### ISSUE THREAD

**Issue by benjaminhr** [acamposuribe/p5.brush#11]
I'm trying to do so animations with the library but the loading time for even a single frame is very slow, are there any plans for improving performance such that animations would be possible? :)

**Comment by acamposuribe** [comment]
Yes, you're right.

As explained in the readme, `The library is designed with texture quality in mind, and may only be suitable for high-resolution artworks, not real-time interactive pieces.`

If we ever want to improve performance, it would need to be via gl shaders, but I don't have the technical knowledge to do so!

**Comment by benjaminhr** [comment]
right - makes sense!
