### ISSUE TITLE
Support for instance mode?

### ISSUE THREAD

**Issue by jbeda** [acamposuribe/p5.brush#13]
Please excuse me if I'm off base here.  I'm a p5.js noob and, pretty much, a javascript noob too.

I'm trying to use NPM and ESM modules to manage things.  Also using esbuild to bundle and do development watch/dev. I've got p5 working along with p5.sound.  It required a bit of hacking.  

My current state is https://github.com/jbeda/p5-stuff/tree/ef086ffd3196f377a5868cc50d7e8b0cfa0ed8c0.

I'm looking to play with p5.brush but, at the moment, it looks like I need to use instance mode (https://p5js.org/reference/#/p5/p5) when using modern ESM modules.  I'm getting errors as it looks like p5.brush doesn't work when you are in instance mode.  For example, the first error I hit is that createGraphics isn't defined.  This is something that is on the instance.

Is this something you are looking at fixing? I may be able to take a run at it if you are amenable.

**Comment by acamposuribe** [comment]
Hi @jbeda!
You're right, instance mode doesn't work at the moment, but it should be an easy fix, I believe.
Will do it in the next few days.

**Comment by Hansterdam** [comment]
Great, looking forward to it. I would also like to incorporate it into a project that uses instance mode.
FYI, when I try to load it, it already gives me this error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'push')
    at Object.blend (p5brush.min.js:14:1)
    at v.<anonymous> (p5brush.min.js:18:1)
    at o (p5.min.js:2:1)
    at Array.forEach (<anonymous>)
    at e.default.redraw (p5.min.js:2:1)
    at _draw (p5.min.js:2:1)
```

**Comment by acamposuribe** [comment]
A quick update:
I've already solved this issue and will push the updates to the code this evening. Currently checking that everything works fine.

**Comment by miracle2k** [comment]
@acamposuribe fantastic, works well for me. thanks for your hard work.

one thing  notice is that if you call load multiple times (for subsequent instances, if you use more than one), the brushes become increasingly larger. this is because of:

```
globalScale(_r.width / 250) // Adjust standard brushes to match canvas
```

during load() which permantly changes the global state.

**Comment by acamposuribe** [comment]
> @acamposuribe fantastic, works well for me. thanks for your hard work.
> 
> one thing notice is that if you call load multiple times (for subsequent instances, if you use more than one), the brushes become increasingly larger. this is because of:
> 
> ```
> globalScale(_r.width / 250) // Adjust standard brushes to match canvas
> ```
> 
> during load() which permantly changes the global state.

Should be fixed

**Comment by acamposuribe** [comment]
> Thank you for getting this fixed! I’ve been sick for the past several days so didn’t have a chance to verify it before you committed.

There were still a few bugs that I (hopefully) resolved today.
Take a second look at the docs again, since you need to load the library for instance mode in a certain way.
