### ISSUE TITLE
brush.point not working

### ISSUE THREAD

**Issue by benjaminhr** [acamposuribe/p5.brush#15]
Given the code: 

```
brush.pick("rotring");
brush.strokeWeight(random(3, 8));
brush.stroke(random(palette));

brush.point(300, 300);
```

Get the error 3 times: 
```
🌸 p5.js says: [p5.brush.js, line 1685] circle() was expecting Number for the first parameter, received NaN instead. (http://p5js.org/reference/#/p5/circle)
```

Using the minified version of the `p5.brush.js` script.

Nothing visible in the UI.

**Comment by acamposuribe** [comment]
Can you create a sketch on the p5 online editor that reproduces the issue?

**Comment by acamposuribe** [comment]
In any case, I do not recommend using the brush.point() function, since it is really designed for people who want to create their own brush paths with complete control over 
In fact, I'm removing the function, since it creates many misunderstandings!

**Comment by benjaminhr** [comment]
Ah ok - makes sense. I guess you can create an equivalent "point" by just using the `brush.circle()` function anyway.
