### ISSUE TITLE
Error with brush.rect

### ISSUE THREAD

**Issue by kala0606** [acamposuribe/p5.brush#23]
Hey so i get this error 'sometimes' :
TypeError: Cannot read properties of undefined (reading 'CENTER')

Error at line 1 in t.rect() in p5.brush.min

am simply using 
`brush.rect(x,y,currWidth,currHeight, CENTER)`

**Comment by acamposuribe** [comment]
> Hey so i get this error 'sometimes' : TypeError: Cannot read properties of undefined (reading 'CENTER')
> 
> Error at line 1 in t.rect() in p5.brush.min
> 
> am simply using `brush.rect(x,y,currWidth,currHeight, CENTER)`

Hi @kala0606,
Could you try using "center", rather than CENTER ?
It might be a problem when using instance mode.
If you are using instance mode, you need to do p.CENTER, probably. Anyway, "center" should work.

**Comment by kala0606** [comment]
Hi @acamposuribe Thanks a lot for your revert.
So i think it might be something else. 

I am able to reproduce the error in the happy grid example https://editor.p5js.org/acamposuribe/sketches/oqlWTatWG when i replace brush.field("truncated") with brush.noField() in the LATEST updated p5brush.js

NOTE: works fine in the older version which is uploaded on the editor there

**Comment by acamposuribe** [comment]
Hi @kala0606 
Apologies for the late reply. So, the problem was with the loading of the library.
It is solved by doing brush.load() after canvas creation.
In any casy, I've edited the code to prevent this from happening. Thx for the feedback
