### ISSUE TITLE
scaleBrushes()

### ISSUE THREAD

**Issue by kala0606** [acamposuribe/p5.brush#24]
Also the brush.scaleBrushes() doesn't seem to scale accurately. If that's a known issue then I will sit tight else here is a small demo test that i made https://editor.p5js.org/ujjwalagarwal/sketches/VaBAeB0wO

if you resize the window which changes innerWidth and innerHeight, the render is different. 

Also i think the fill scales properly, it's the hatch and probably stroke thats an issue.

![download - 2024-02-15T221801 600](https://github.com/acamposuribe/p5.brush/assets/99329125/8c5d8733-626a-4d46-bc33-80b51763d826)
![download (100)](https://github.com/acamposuribe/p5.brush/assets/99329125/411f06d1-8b70-4558-aab4-542dfcf89602)

**Comment by acamposuribe** [comment]
@kala0606 
Yes, that's right. It's how the library works. I can remove this behaviour, but I'd really suggest to avoid resizing the canvas if possible, because many other things can break.
My suggestion would be to use css resize, rather than canvas resize.

**Comment by kala0606** [comment]
Got it. Thank you so much.
