### ISSUE TITLE
Brush.fill() doesn't respect p5 clipping

### ISSUE THREAD

**Issue by fridgebuzz** [acamposuribe/p5.brush#25]
I didn't actually expect this to work, and maybe it's just too hard to do, but FYI: I created a clip mask using

```javascript
beginClip()
drawSomeStuff()
endClip()

brush.push()
brush.noStroke()
brush.fill(fillColor, 100)
brush.bleed(0.3, "out")
brush.rect(0,0,width,height)
brush.noFill()
brush.pop()
```
I hoped the fill would respect the mask but it did not. Would be a nice to have, but I'll live if it doesn't happen. :) Thanks for the great library!

**Comment by acamposuribe** [comment]
Hi @fridgebuzz 
Indeed, that would be a bit complex to implement!
However you can clip with rectangles with brush.clip(clippingRegion) and brush.noClip()
There's some more info on the readme / docs
Hopefully that helps a bit
