### ISSUE TITLE
Marker/Marker2 Crashes on Buffer with WEBGL Errors

### ISSUE THREAD

**Issue by t8ddw** [acamposuribe/p5.brush#26]
Using a buffer createGraphics setup. Works fine with all brushes, except for Marker / Marker2 which throws WEBGL errors around Shader. 

Marker brushes work fine to the main canvas, not throws error on Buffer usage.

Spent hours unwinding my code base, just to realise it was these 2 brush presets, everything else works fine.

Hope this can be resolved, as was the marker effect I was specifically after.

**Comment by acamposuribe** [comment]
Hi @t8ddw 
I cannot reproduce the error. Could you provide the part of your code that is giving you problems?
