### ISSUE TITLE
What is seeds?

### ISSUE THREAD

**Issue by NahuelGerthVK** [acamposuribe/p5.brush#28]
Hi there :-)

in your examples I noticed you used seeds sometimes:

```js
// p5.brush variables
let seeds = [];

// setup
// p5.brush settings
for (let i = 0; i < 150; i++) seeds.push(random());

// draw
randomSeed(33213 * seeds[67]);
brush.circle(155, 140, 50);
```

Can you explain a little what this is and what it does?

Thank you for this great library!
Nahuel

edit: I am especially curious how you picked the numbers, eg. 150, 33213, 67. Is there some logic behind this?

**Comment by acamposuribe** [comment]
Hi @NahuelGerthVK 
You can read about an equivalent seed function here: https://p5js.org/reference/#/p5/randomSeed
