### ISSUE TITLE
Readme has two small errors

### ISSUE THREAD

**Issue by bergonom** [acamposuribe/p5.brush#30]
In the 'Usage' section of [the brush.add() details](https://github.com/acamposuribe/p5.brush?tab=readme-ov-file#brush-management), I think there are two mistakes in one of the examples.

1. I think the value for `pressure.type` should be "standard". The "custom" type requires the `pressure.curve` value to be a function.
2. There should be a comma after the "tip" value

```
// You create a custom tip brush like this:
brush.add("watercolor", {
    type: "custom",
    weight: 5,
    vibration: 0.08,
    opacity: 23,
    spacing: 0.6,
    blend: true,
    pressure: {
        type: "custom",
        min_max: [1.35,1],
        curve: [0.35,0.25] // Values for the bell curve
    },
    tip: (_m) => {
       // in this example, the tip is composed of two squares, rotated 45 degrees
       // Always execute drawing functions within the _m buffer!
       _m.rotate(45), _m.rect(-1.5,-1.5,3,3), _m.rect(1,1,1,1);
    }
    rotate: "natural",
})
```

Thanks for this amazing library!

**Comment by acamposuribe** [comment]
Hey @bergonom, **thx a lot** for spotting this mistakes. Already fixed them
