### ISSUE TITLE
Could this brush be used in tldraw?

### ISSUE THREAD

**Issue by andupotorac** [acamposuribe/p5.brush#33]
I'd love to give it a try, but I am unsure if it would work.

**Comment by andupotorac** [comment]
Follow-up question on this @acamposuribe. What would be the best approach to take if we were to have the library redraw based on some bezier curves / pre-drawn lines? Would this even be doable? Would we need to use the position to send it the coordinates as such, or is there a better approach?

**Comment by acamposuribe** [comment]
Hi @andupotorac !
I've never used tldraw... so I have no idea

As for your second question...
I would say it's best to provide coordinates and use beginShape(), vertex(), and endShape()
