### ISSUE TITLE
Noise appears when brushes are superimposed

### ISSUE THREAD

**Issue by Suyens** [acamposuribe/p5.brush#34]
Hello, when you use a marker brush to paint continuously on the canvas, there will be variegated colors. What is the problem?
![image](https://github.com/user-attachments/assets/40b243bc-80ca-41e6-a8c3-c6eec1afde2c)

**Comment by acamposuribe** [comment]
Hi @Suyens 
This is a result of how the color mixing process works, using webgl.
The process introduces make it look more natural, and it can go crazy if you paint many lines on top of each other.
Is it too bothersome for your project? I could see if an option can be added to avoid the noise, but might take a while!

**Comment by Metamere** [comment]
I think it is good in moderation, but yeah, it might be nice to be able to tame it a bit when a lot of overlaps are desired of unavoidable.
