### ISSUE TITLE
Arc Support

### ISSUE THREAD

**Issue by literalmonkey** [acamposuribe/p5.brush#6]
Adding support for arcs would be amazing. Not an issue or a need to have but it would be an very nice to have. Either way, this library is incredible. Thank you!

**Comment by acamposuribe** [comment]
Thx for the proposal!
Do you mean something similar to the arc() method in p5?
I'd also like to include bezier curves in the next big update. 
Will add arc to the list, it should be easy to do it with the Plot class.

**Comment by literalmonkey** [comment]
yes! arc() would be awesome! for my particular purpose i am using making them as a custom shape and using the watercolor fill. Though, I think for this type of usage it might still need to be a custom shape. 
![watercolor arc](https://github.com/acamposuribe/p5.brush/assets/137670086/2f21b4a9-4a98-4664-89ba-843cf87627c2)
Not sure if it is technically possible, but perhaps watercolor as a stroke option where it's fill area is based on strokeweight may be possible in the future.
