### ISSUE TITLE
Issues when attempting to rotate()

### ISSUE THREAD

**Issue by Ethspresso** [acamposuribe/p5.brush#7]
While exploring your excellent library, I tried to draw a flower shape by drawing lines and rotating. However this did not have the expected result. I expected rotate() to transform coordinates so that the same shape got duplicated in a new direction, but instead it seems like the loop below just draws the same shape in the same location each time it runs:
```
function setup() {
  createCanvas(600, 600, WEBGL);
  angleMode(DEGREES);
  noLoop();  
  brush.scale(2);
}

function draw() {
  push();
  brush.set("pen", "black", 2);
  let angle = 360/6;
  let x = 0;
  let y = 0;
  for (let j = 0; j < 6; j++) {
    brush.spline([[x, y], [x-30, y+50], [x-30, y+100], [x, y+200]], 1);
    brush.spline([[x, y], [x-5, y+50], [x-5, y+100], [x, y+200]], 1.5);
    brush.spline([[x, y], [x+30, y+50], [x+30, y+100], [x, y+200]], 1.5);
    brush.spline([[x, y], [x+50, y+50], [x+50, y+100], [x, y+200]], 1);
    rotate(angle);
  }
  pop();
}
```

Is there any obvious reason that I'm not realizing for why rotate() does not seem to do what I expect here?

**Comment by acamposuribe** [comment]
Yes, you're right.
You cannot use rotate() to affect the library geometries, and it would actually create many problems.
Going to introduce a brush.rotate() function soon, but it would require some work, and probably also brush.push() and brush.pop() functions....

**Comment by Ethspresso** [comment]
Thanks for confirming, I can make workarounds for now :)

**Comment by acamposuribe** [comment]
> Thanks for confirming, I can make workarounds for now :)

Heyo Ethspresso,
I added a brush.rotate() function. You should be able to use that one, as well as brush.push() and brush.pop() which work similarly to the main push and pop functions in p5.
